idf_component_register(
    SRCS
        "main.c"
        "storage_credentials.c"
        "storage_fs.c"
        "storage_web.c"
        "widget_runtime.c"
        "network_manager.c"
        "time_service.c"
        "web_setup.c"
        "ota_manager.c"
        "display_ota.c"
    INCLUDE_DIRS "."
    REQUIRES
        nvs_flash
        spiffs
        esp_wifi
        esp_event
        esp_netif
        esp_http_server
        esp_http_client
        app_update
        esp_partition
        mbedtls
        json
        esp_lcd
        esp_driver_i2c
        esp_driver_gpio
        esp_timer
        lvgl__lvgl
        espressif__esp_lcd_touch
        espressif__esp_lcd_touch_gt911
)
